function FigModify(h,name)
figure(h);box on
set(gca,'FontSize',16)
set(gca,...
'Units','normalized',...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',16,...
'FontName','Calibri')
set(h,'Units','Inches');
pos = get(h,'Position');
set(h,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
print(h, '-dtiff', [name,'.tif']);
